// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhhmelncqrtolfhqtocm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoaG1lbG5jcXJ0b2xmaHF0b2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzMzNzcsImV4cCI6MjA2ODQ0OTM3N30._dcpTQuMs9K5OfxNZkp-6m5jLKaz0qHCHtv_dDbzarY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});